<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>RetwhoConnector.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="SocketIOClient" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="ZstdSharp.Port" />
  </ItemGroup>
</Project>
